name:                haskell-parconc-examples
version:             0.1.0.0
github:              "rolandtritsch/haskell-parconc-examples"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2018 Roland Tritsch"

extra-source-files:
- README.md

description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5
- timeit
- bytestring
- async
- HTTP
- network-uri
- stm
- containers
- network

library:
  source-dirs: src
  dependencies:
  - containers

executables:
  chapter01-exe:
    main:                Chapter01.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter01
    dependencies:
    - haskell-parconc-examples

  chapter07fork-exe:
    main:                Chapter07Fork.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter07Fork
    dependencies:
    - haskell-parconc-examples

  chapter07reminders-exe:
    main:                Chapter07Reminders.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter07Reminders
    dependencies:
    - haskell-parconc-examples

  chapter07mvars-exe:
    main:                Chapter07MVars.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter07MVars
    dependencies:
    - haskell-parconc-examples

  chapter07logger-exe:
    main:                Chapter07Logger.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter07Logger
    dependencies:
    - haskell-parconc-examples

  chapter07phonebook-exe:
    main:                Chapter07PhoneBook.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter07PhoneBook
    dependencies:
    - haskell-parconc-examples

  chapter08geturlstimed-exe:
    main:                Chapter08GetURLsTimed.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter08GetURLsTimed
    dependencies:
    - haskell-parconc-examples

  chapter08geturlsfirst-exe:
    main:                Chapter08GetURLsFirst.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter08GetURLsFirst
    dependencies:
    - haskell-parconc-examples

  chapter09catchmask-exe:
    main:                Chapter09CatchMask.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter09CatchMask
    dependencies:
    - haskell-parconc-examples

  chapter10windowman-exe:
    main:                Chapter10WindowMan.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter10WindowMan
    dependencies:
    - haskell-parconc-examples

  chapter12server-exe:
    main:                Chapter12Server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter12Server
    dependencies:
    - haskell-parconc-examples

  chapter12serverstm-exe:
    main:                Chapter12ServerSTM.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter12ServerSTM
    dependencies:
    - haskell-parconc-examples
