name:                haskell-parcon-examples
version:             0.1.0.0
github:              "rolandtritsch/haskell-parcon-examples"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2018 Roland Tritsch"

extra-source-files:
- README.md

description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  chapter01-exe:
    main:                Chapter01.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter01
    dependencies:
    - haskell-parcon-examples

  chapter07fork-exe:
    main:                Chapter07Fork.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chapter07Fork
    dependencies:
    - haskell-parcon-examples
